version: "3"
services:
  pod_downscale:
    container_name: downscale 
    build: ./compression
    #restart: always
    volumes:
      - ./videos:/videos
      - ./videoscomp:/videoscomp  

  lang_ident:
    image: lang_ident
    environment:
      START_TIME: "00:00:10"
      DURATION: "00:00:05"
    build:
      context: ./podAdrien/lang_ident
      dockerfile: Dockerfile
    volumes:
      - ./podAdrien/lang_ident/sample_data:/sample_data

  subtitle:
    image: subtitle
    build:
      context: ./Clouding
      dockerfile: Dockerfile
    depends_on:
      - lang_ident
    volumes:
      - ./Clouding/videos:/videos

