version: "3"
services:
  lang_ident:
    build:
      context: ./podAdrien/lang_ident
    volumes:
      - ./podAdrien/land_ident/sample_data:/sample_data
    environment:
      start_time: 10
      duration: 05
    command: >
      /bin/bash -c "ffmpeg -i /app/videos/video.mp4 -vn -ar 48000 -ac 1 -ab 192k -f wav /app/audio/output.wav &&
      ffmpeg -i /app/audio/output.wav -ss ${START_TIME} -t ${DURATION} /app/audio/output_cut.wav"
      CMD ["python", "lang_ident.py"]

  autosub:
    build:
      context: ./Clouding
    volumes:
      - ./Clouding/videos:/videos
    command: >
      /bin/bash -c "autosub /videos/video.mp4"
