version: "3"
services:
  #pod_downscale:
    #container_name: downscale 
    #build: ./compression
    #volumes:
      #- ./videos:/videos
      #- ./videoscomp:/videoscomp  

  lang_ident:
    image: bodrien/lang_ident:tag
    environment:
      START_TIME: "00:00:10"
      DURATION: "00:00:05"
    build:
      context: ./podAdrien/lang_ident
      dockerfile: Dockerfile
    volumes:
      - ./videos:/videos

  subtitle:
    image: subtitle
    build:
      context: ./Clouding
      dockerfile: Dockerfile
    depends_on:
      lang_ident:
        condition: service_completed_successfully
    volumes:
      - ./videos:/videos

  storage:
    image: alpine:latest
    volumes :
      - ./storage:/storage
      - ./videos:/videos
    depends_on:
      subtitle:
        condition: service_completed_successfully
    command: sh -c "cp -r /videos/* /storage/ && rm -r /videos/*"

