FROM tensorflow/tensorflow

WORKDIR .
COPY langIdent.py .
COPY AttRnn7lang ./AttRnn7lang/
COPY loutre_cut.wav .

RUN pip install -q -U pip==20.2
# RUN pip install -q tensorflow
RUN pip install scipy
RUN pip install -q ffmpeg-python

CMD ["python","langIdent.py"]